# Travis CI config for AppStream

language: c
sudo: required
dist: trusty

services:
  - docker

compiler:
  - gcc
  - clang

before_script:
  - docker build -t appstream -f tests/ci/Dockerfile .
  - if [ "$CC" = "clang" ]; then export CXX="clang++" CC="clang"; fi
  - if [ "$CC" = "gcc" ]; then export CXX="g++-6" CC="gcc-6"; fi

script:
  - docker run -t -e CC=$CC -e CXX=$CXX -v `pwd`:/build appstream
    ./tests/ci/build_and_test.sh
