name: Build Test

on: [push, pull_request]

jobs:
  build-debian-stable:
    name: Debian Stable
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cd tests/ci/ && docker build -t appstream -f ./Dockerfile-debian-stable .

    - name: Build & Test
      run: docker run -t -e COMPILER_VENDOR=$CVENDOR -e CC=gcc -e CXX=g++ -v `pwd`:/build appstream
           ./tests/ci/build-and-test.sh


  build-debian-testing:
    name: Debian Testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cd tests/ci/ && docker build -t appstream -f ./Dockerfile-debian-testing .

    - name: Build & Test
      run: docker run -t -e COMPILER_VENDOR=$CVENDOR -e CC=gcc -e CXX=g++ -v `pwd`:/build appstream
           ./tests/ci/build-and-test.sh


  build-ubuntu:
    name: Ubuntu LTS
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: sudo ./tests/ci/install-deps-deb.sh
      
    - name: Build & Test
      run: CC=gcc CXX=g++ ./tests/ci/build-and-test.sh
